In [15]:
import pandas as pd
import itertools

In [5]:
total_pdb_df = pd.read_csv("total.tsv", sep='\t')

unique_pdb = pd.DataFrame()
for column_name, column_data in total_pdb_df.items():
    for pdb in column_data:
        unique_pdb.loc[pdb, column_name] = 'o'
        
unique_pdb = unique_pdb.loc[~unique_pdb.index.isna()].fillna('x')

unique_pdb.to_csv('unique_pdb.csv')

unique_pdb

     TRAIT STCRDab TCR3d ATLAS IEDB VDJdb
7sg2     o       o     o     x    o     o
7sg0     o       x     o     x    o     o
7rtr     o       o     o     x    x     o
7rrg     o       x     o     x    o     o
7rm4     o       o     o     x    o     o
...    ...     ...   ...   ...  ...   ...
6mt3     x       x     x     x    x     o
8rnh     x       x     x     x    x     o
8rop     x       x     x     x    x     o
8rng     x       x     x     x    x     o
4wuu     x       x     x     x    x     o

[296 rows x 6 columns]

## Species check

In [3]:
pdb_df = pd.read_csv("STCRDab/pdb.csv")
pdb_df

,PDB,Species,Method,Resolution,Affinity,TCR_Chains
0,8trq,mouse,X-RAY DIFFRACTION,2.75,NaN,TCR no. 1VB: EVA: D
1,3qux,mouse,X-RAY DIFFRACTION,2.91,NaN,TCR no. 1VB: DVA: C
2,4ozi,human,X-RAY DIFFRACTION,3.2,NaN,TCR no. 1VB: HVA: GTCR no. 2VB: FVA: E
3,2ak4,human,X-RAY DIFFRACTION,2.5,NaN,TCR no. 1VB: EVA: DTCR no. 2VB: JVA: ITCR no. ...
4,2aq3,mouse,X-RAY DIFFRACTION,2.3,NaN,TCR no. 1VB: GTCR no. 2VB: ETCR no. 3VB: CTCR ...
...,...,...,...,...,...,...
629,6fup,human,X-RAY DIFFRACTION,1.72,NaN,TCR no. 1VB: BVA: A
630,7zt2,human,X-RAY DIFFRACTION,2.4,NaN,TCR no. 1VB: EVA: D
631,6miv,mouse,X-RAY DIFFRACTION,2.05,NaN,TCR no. 1VB: DVA: C
632,3rtq,mouse,X-RAY DIFFRACTION,2.8,NaN,TCR no. 1VB: DVA: C
633,2apf,mouse,X-RAY DIFFRACTION,1.8,NaN,TCR no. 1VB: A

In [ ]:
mouse_pdb = pdb_df.loc[pdb_df['Species']=='mouse', 'PDB'].tolist()

['8trq',
 '3qux',
 '2aq3',
 '6v18',
 '3o8x',
 '1sbb',
 '3tpu',
 '4p2o',
 '8i5c',
 '2z35',
 '1kb5',
 '3e2h',
 '6c68',
 '1kj2',
 '6mja',
 '3pqy',
 '6v15',
 '3owe',
 '8wul',
 '6v19',
 '7rdv',
 '3e3q',
 '4ms8',
 '5til',
 '3qi9',
 '3r8b',
 '6mj4',
 '6cw9',
 '6dfv',
 '8d5p',
 '1l0x',
 '6mng',
 '5iw1',
 '6mkd',
 '3arg',
 '3rug',
 '3byy',
 '4elm',
 '3qiu',
 '3bzd',
 '6c61',
 '3tvm',
 '3mc0',
 '2q86',
 '3rdt',
 '3byt',
 '5m00',
 '4ei5',
 '4p2r',
 '4p2q',
 '5tje',
 '3q5y',
 '6dfq',
 '2j8u',
 '2aq2',
 '3tf7',
 '3ard',
 '1lp9',
 '1nfd',
 '4mxq',
 '6omg',
 '2p1y',
 '3ta3',
 '6bnl',
 '1g6r',
 '4zak',
 '4y16',
 '5wlg',
 '2aq1',
 '3quz',
 '3c6l',
 '6miy',
 '3rgv',
 '1h5b',
 '3c5z',
 '2e7l',
 '1ac6',
 '3mbe',
 '5m01',
 '7l15',
 '6mra',
 '5swz',
 '7n5c',
 '8trr',
 '6cwb',
 '2ol3',
 '2apt',
 '4apq',
 '8wte',
 '3mff',
 '4p5t',
 '3qjh',
 '6mj6',
 '6cx5',
 '6mno',
 '7na5',
 '5m02',
 '3axl',
 '2ckb',
 '3tfk',
 '3are',
 '2uwe',
 '8i5d',
 '7jwj',
 '3tn0',
 '6mnn',
 '4ei6',
 '6cxa',
 '5vcj',
 '1bwm',
 '4mvb',
 '6cwe',
 '6cx9',
 '1d9k',
 '4p46',
 '6mji',
 '4n0c',
 '2apw',
 '6xng',
 '1mwa',
 '4irs',
 '7n5p',
 '3to4',
 '1jck',
 '6dfw',
 '6mjq',
 '4n5e',
 '3sdc',
 '3qiw',
 '4y4k',
 '1nam',
 '3qjf',
 '3c60',
 '4nhu',
 '8vz9',
 '6mnm',
 '1i9e',
 '4y4f',
 '3sdd',
 '3arf',
 '6dfs',
 '3he7',
 '4p23',
 '6bnk',
 '4elk',
 '2jcc',
 '3o9w',
 '6g9q',
 '1b88',
 '3quy',
 '6cxe',
 '2oi9',
 '7z50',
 '3arb',
 '6bga',
 '6mjj',
 '7f5k',
 '3he6',
 '6mss',
 '2apx',
 '4y4h',
 '1l0y',
 '3tjh',
 '3sda',
 '2apv',
 '7m72',
 '5ivx',
 '6v0y',
 '2pxy',
 '3qib',
 '6v1a',
 '8t4z',
 '8vz8',
 '1u3h',
 '7n4k',
 '2z31',
 '6mkr',
 '3scm',
 '3q5t',
 '1tcr',
 '5sws',
 '7k0x',
 '1fo0',
 '7jwi',
 '8d5q',
 '6cw6',
 '4y2d',
 '4irj',
 '3rzc',
 '1bec',
 '6v13',
 '2apb',
 '6miv',
 '3rtq',
 '2apf']

In [5]:
suspect_pdb_df = unique_pdb.loc[unique_pdb.index.isin(mouse_pdb)]
suspect_pdb_df

     TRAIT STCRDab TCR3d ATLAS IEDB VDJdb
2uwe     o       x     o     x    o     o
1lp9     o       o     o     o    o     o
8wte     o       o     o     x    o     x
8i5c     x       o     o     x    o     x
8wul     x       o     o     x    o     x
8trr     x       o     o     x    o     x
8i5d     x       o     o     x    o     x
2jcc     x       o     o     x    o     o
2j8u     x       x     o     x    o     o
6v0y     x       x     o     x    o     x
6v13     x       x     o     x    o     x
6v15     x       x     o     x    o     x
6v18     x       x     o     x    o     x
6v19     x       x     o     x    o     x
6v1a     x       x     o     x    o     x
8trq     x       x     o     x    o     x

In [6]:
pdb_df.loc[pdb_df['PDB'].isin(suspect_pdb_df.index.tolist())]

,PDB,Species,Method,Resolution,Affinity,TCR_Chains
0,8trq,mouse,X-RAY DIFFRACTION,2.75,NaN,TCR no. 1VB: EVA: D
9,6v18,mouse,X-RAY DIFFRACTION,2.35,NaN,TCR no. 1VB: EVA: D
32,8i5c,mouse,X-RAY DIFFRACTION,3.34,NaN,TCR no. 1VB: OVA: NTCR no. 2VB: TVA: STCR no. ...
64,6v15,mouse,X-RAY DIFFRACTION,2.8,NaN,TCR no. 1VB: EVA: D
74,8wul,mouse,X-RAY DIFFRACTION,2.36,NaN,TCR no. 1VB: FVA: ETCR no. 2VB: BVA: ATCR no. ...
82,6v19,mouse,X-RAY DIFFRACTION,2.6,NaN,TCR no. 1VB: EVA: D
198,2j8u,mouse,X-RAY DIFFRACTION,2.88,NaN,TCR no. 1VB: MVA: LTCR no. 2VB: FVA: E
203,1lp9,mouse,X-RAY DIFFRACTION,2,NaN,TCR no. 1VB: MVA: LTCR no. 2VB: FVA: E
286,8trr,mouse,X-RAY DIFFRACTION,2.65,NaN,TCR no. 1VB: JVA: ITCR no. 2VB: EVA: D
304,8wte,mouse,X-RAY DIFFRACTION,2.17,NaN,TCR no. 1VB: BVA: ATCR no. 2VB: DVA: C
339,2uwe,mouse,X-RAY DIFFRACTION,2.4,NaN,TCR no. 1VB: FVA: ETCR no. 2VB: MVA: L
345,8i5d,mouse,X-RAY DIFFRACTION,3.3,NaN,TCR no. 1VB: BVA: A
478,2jcc,mouse,X-RAY DIFFRACTION,2.5,NaN,TCR no. 1VB: FVA: ETCR no. 2VB: MVA: L
540,6v0y,mouse,X-RAY DIFFRACTION,2.7,NaN,TCR no. 1VB: EVA: D
561,6v1a,mouse,X-RAY DIFFRACTION,2.29,NaN,TCR no. 1VB: EVA: D
614,6v13,mouse,X-RAY DIFFRACTION,2.75,NaN,TCR no. 1VB: EVA: D

In [7]:
suspect_pdb_df.index

Index(['2uwe', '1lp9', '8wte', '8i5c', '8wul', '8trr', '8i5d', '2jcc', '2j8u',
       '6v0y', '6v13', '6v15', '6v18', '6v19', '6v1a', '8trq'],
      dtype='object')

## Drop duplicates

In [ ]:
# # drop duplicates on raw db
pdbs = {}
for db in ['TRAIT',	'STCRDab', 'TCR3d', 'ATLAS', 'IEDB', 'VDJdb']:
    with open(f'{db}/0.pdb.txt', 'r') as f:
        pdbs[db] = f.read().split()

pdbs = set(itertools.chain.from_iterable(pdbs.values()))
with open("drop_duplicates/0.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in pdbs]))
len(pdbs)

1109

In [ ]:
# drop duplicates using filter level 1
pdbs = {}
for db in ['TRAIT',	'STCRDab', 'TCR3d', 'ATLAS', 'IEDB', 'VDJdb']:
    with open(f'{db}/1.pdb.txt', 'r') as f:
        pdbs[db] = f.read().split()

pdbs = set(itertools.chain.from_iterable(pdbs.values()))
with open("drop_duplicates/1.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in pdbs]))
len(pdbs)

371

In [ ]:
# drop duplicates using filter level 2
pdbs = {}
for db in ['TRAIT',	'STCRDab', 'TCR3d', 'ATLAS', 'IEDB', 'VDJdb']:
    with open(f'{db}/2.pdb.txt', 'r') as f:
        pdbs[db] = f.read().split()
        
pdbs = set(itertools.chain.from_iterable(pdbs.values()))
with open("drop_duplicates/2.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in pdbs]))
len(pdbs)

371

In [ ]:
# drop duplicates using filter level 3
pdbs = {}
for db in ['TRAIT',	'STCRDab', 'TCR3d', 'ATLAS', 'IEDB', 'VDJdb']:
    with open(f'{db}/3.pdb.txt', 'r') as f:
        pdbs[db] = f.read().split()
        
pdbs = set(itertools.chain.from_iterable(pdbs.values()))
with open("drop_duplicates/3.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in pdbs]))
len(pdbs)

296

## extract hla_id using pdb

In [ ]:
hla_df = pd.DataFrame()

# HLA merge
pdbs = {}
for db in ['TRAIT',	'STCRDab', 'TCR3d', 'ATLAS', 'IEDB', 'VDJdb']:
    _df = pd.read_csv(f'{db}/{db}_hla.csv').set_index('pdb')
    print(db, len(_df), _df.index.tolist())
    
    hla_df = pd.concat([hla_df, _df], axis=1)
hla_df

TRAIT 192 ['7sg2', '7sg0', '7rtr', '7rrg', '7rm4', '7ndu', '7ndq', '7n6e', '7n1f', '7n1e', '7l1d', '7dzn', '7dzm', '6zkz', '6zkx', '6zkw', '6xcp', '6xco', '6xc9', '6vrn', '6vrm', '6vqo', '6vmx', '6vmc', '6vma', '6vm8', '6vm7', '6uln', '6uon', '6ulk', '6uli', '6ulr', '6u3o', '6u3n', '6tro', '6tmo', '6rsy', '6rpb', '6rpa', '6rp9', '6r2l', '6q3s', '6py2', '6px6', '6p64', '6mtm', '6eqb', '6eqa', '6dxf', '6dkp', '6dfx', '6d78', '6cqr', '6cqq', '6cqn', '6bj8', '6bj3', '6bj2', '6avg', '6avf', '6amu', '6am5', '5yxu', '5yxn', '5xov', '5xot', '5wkh', '5wkf', '5w1w', '5w1v', '5tez', '5nqk', '5nmg', '5nmf', '5nme', '5nht', '5men', '5ksb', '5ksa', '5ks9', '5jzi', '5jhd', '5isz', '5hyj', '5hho', '5hhm', '5euo', '5eu6', '5e9d', '5e6i', '5d2n', '5d2l', '5c0c', '5c0b', '5c0a', '5c09', '5c08', '5c07', '5bs0', '5brz', '56i', '4zez', '4z7w', '4z7v', '4z7u', '4y1a', '4y19', '4qrr', '4qrp', '4qok', '4prp', '4pri', '4prh', '4p4k', '4ozi', '4ozh', '4ozg', '4ozf', '4mnq', '4mji', '4l3e', '4jry', '4jrx', '4jff', '4jfe', '4jfd', '4h1l', '4grl', '4gg6', '4g9f', '4g8g', '4ftv', '4euq', '4eup', '4c56', '3vxs', '3qdm', '3qdj', '3qdg', '3pwp', '3pl6', '3o6f', '3o4l', '3nfj', '3mv9', '3kxf', '3kps', '3kpr', '3hg1', '3h9s', '3gsn', '3ffc', '3dxa', '3d3v', '2ypl', '2xn9', '2wbj', '2vlr', '2vlk', '2uwe', '2pye', '2nx5', '2ian', '2iam', '2ial', '2gj6', '2f54', '1qrn', '1oga', '1mi5', '1lp9', '1j8h', '1fyt', '1bd2', '1ao7', '3vxr', '3vxm', '3utt', '3t0e', '3sjv', '3qfj', '3qeq', '2f53', '2esv', '2bnr', '2bnq', '2ak4', '1zgl', '1ymm', '1qsf', '1qse', '8wte']
STCRDab 158 ['2ak4', '5eu6', '8eo8', '5wkh', '7t2b', '7sg1', '3w0w', '5w1v', '6avf', '5nht', '5jzi', '8i5c', '6am5', '3mv8', '3kpr', '5hyj', '7t2d', '6rpb', '1zgl', '6avg', '7rm4', '3pwp', '7n6e', '8wul', '3dxa', '6rp9', '4mji', '6vmx', '3qdj', '6bj2', '3qdm', '7rtr', '8en8', '1ymm', '5c07', '3vxu', '6vqo', '1j8h', '8enh', '6zkz', '6tmo', '5wkf', '8shi', '6vrn', '5d2n', '6mtm', '5bs0', '7n2q', '6eqb', '5e6i', '1lp9', '3kps', '5w1w', '7pdw', '5c09', '3sjv', '1qrn', '3kxf', '5c0a', '7n2n', '8es9', '2nx5', '8gvb', '8trl', '5d2l', '5nmg', '7dzm', '5hho', '1qse', '7ndt', '5nmf', '8gvi', '8trr', '7qpj', '3vxm', '6eqa', '7rk7', '8wte', '1qsf', '3qdg', '8cx4', '4pri', '8ye4', '7n2s', '5c08', '8i5d', '5jhd', '6py2', '7dzn', '7ndu', '4eup', '7n1e', '3qeq', '3vxr', '3d3v', '5isz', '6rsy', '1mi5', '3vxs', '7ow5', '8gvg', '7ndq', '8gom', '5hhm', '5c0b', '8es8', '7pb2', '4qrp', '6rpa', '7n1f', '5c0c', '6d78', '4jrx', '6zkx', '5yxu', '7sg2', '8gon', '2jcc', '6dkp', '5nqk', '8f5a', '7pbc', '3mv7', '5yxn', '5e9d', '6amu', '5brz', '3h9s', '4prp', '5nme', '7t2c', '4g9f', '7n2o', '5tez', '3d39', '6zkw', '4ftv', '6px6', '2esv', '5euo', '6zky', '6tro', '7n2p', '7r80', '1bd2', '4l3e', '3ffc', '4jry', '6uz1', '6vrm', '7n2r', '1fyt', '3qfj', '3gsn', '7ow6', '3mv9', '6q3s', '1ao7']
TCR3d 279 ['1ao7', '1bd2', '1fyt', '1j8h', '1lp9', '1mi5', '1oga', '1qrn', '1qse', '1qsf', '1ymm', '1zgl', '2ak4', '2bnq', '2bnr', '2esv', '2f53', '2f54', '2gj6', '2iam', '2ian', '2j8u', '2jcc', '2nx5', '2p5e', '2p5w', '2pye', '2uwe', '2vlj', '2vlk', '2vlr', '2wbj', '2ypl', '3d39', '3d3v', '3dxa', '3ffc', '3gsn', '3h9s', '3hg1', '3kpr', '3kps', '3kxf', '3mv7', '3mv8', '3mv9', '3o4l', '3o6f', '3pl6', '3pwp', '3qdg', '3qdj', '3qdm', '3qeq', '3qfj', '3sjv', '3t0e', '3uts', '3utt', '3vxm', '3vxr', '3vxs', '3vxu', '3w0w', '4e41', '4eup', '4ftv', '4g8g', '4g9f', '4gg6', '4grl', '4h1l', '4jfd', '4jfe', '4jff', '4jrx', '4jry', '4l3e', '4may', '4mji', '4mnq', '4ozf', '4ozg', '4ozh', '4ozi', '4p4k', '4prh', '4pri', '4prp', '4qok', '4qrp', '4qrr', '4y19', '4y1a', '4z7u', '4z7v', '4z7w', '5brz', '5bs0', '5c07', '5c08', '5c09', '5c0a', '5c0b', '5c0c', '5d2l', '5d2n', '5e6i', '5e9d', '5eu6', '5euo', '5hhm', '5hho', '5hyj', '5isz', '5jhd', '5jzi', '5ks9', '5ksa', '5ksb', '5men', '5nht', '5nme', '5nmf', '5nmg', '5nqk', '5tez', '5w1v', '5w1w', '5wkf', '5wkh', '5xot', '5xov', '5yxn', '5yxu', '6am5', '6amu', '6avf', '6avg', '6bj2', '6bj3', '6bj8', '6cql', '6cqn', '6cqq', '6cqr', '6d78', '6dfx', '6dkp', '6eqa', '6eqb', '6mtm', '6p64', '6px6', '6py2', '6q3s', '6r0e', '6r2l', '6rp9', '6rpa', '6rpb', '6rsy', '6tmo', '6tro', '6u3n', '6u3o', '6uk2', '6uk4', '6uln', '6ulr', '6uon', '6uz1', '6v0y', '6v13', '6v15', '6v18', '6v19', '6v1a', '6vm7', '6vm8', '6vm9', '6vma', '6vmc', '6vmx', '6vqo', '6vrm', '6vrn', '6xc9', '6xco', '6xcp', '6zkw', '6zkx', '6zky', '6zkz', '7dzm', '7dzn', '7l1d', '7n1e', '7n1f', '7n2n', '7n2o', '7n2p', '7n2q', '7n2r', '7n2s', '7n6e', '7ndq', '7ndt', '7ndu', '7nme', '7nmf', '7nmg', '7ow5', '7ow6', '7pb2', '7pbc', '7pbe', '7pdw', '7phr', '7q99', '7q9a', '7q9b', '7qpj', '7r80', '7rk7', '7rm4', '7rrg', '7rtr', '7sg0', '7sg1', '7sg2', '7su9', '7t2b', '7t2c', '7t2d', '8cx4', '8dnt', '8en8', '8enh', '8eo8', '8es8', '8es9', '8f5a', '8gom', '8gon', '8gvb', '8gvg', '8gvi', '8i5c', '8i5d', '8pjg', '8qfy', '8rj5', '8rlt', '8rlu', '8rlv', '8rro', '8rym', '8ryn', '8ryo', '8ryp', '8ryq', '8shi', '8trl', '8trq', '8trr', '8v4z', '8v50', '8v51', '8vcx', '8vcy', '8vd0', '8vd2', '8wte', '8wul', '8ye4', '8yiv', '8yj2', '9c3e']
ATLAS 69 ['1mi5', '2vlj', '2vlr', '1ao7', '3gsn', '3hg1', '3mv7', '3mv9', '3mv8', '3o6f', '1qse', '1qrn', '1qsf', '2esv', '3dxa', '3h9s', '3kpr', '3kps', '2ak4', '3kxf', '3o4l', '3pl6', '3pwp', '3qdg', '3qdj', '3qdm', '3qeq', '3qfj', '4jff', '4jfd', '4jfe', '3utt', '2bnr', '2bnq', '4ftv', '4mnq', '3vxr', '3vxs', '3vxu', '3vxm', '4gg6', '4z7u', '4z7v', '4h1l', '4jrx', '4jry', '4mji', '4ozi', '4ozh', '4ozf', '4ozg', '4pri', '4prh', '4qok', '4qrp', '4g8g', '4g9f', '2f54', '2f53', '2p5e', '2p5w', '3ffc', '4z7w', '4l3e', '1fyt', '1bd2', '1lp9', '5d2n', '5d2l']
IEDB 241 ['1oga', '1fyt', '1j8h', '1mi5', '1bd2', '1qse', '1qrn', '1qsf', '1ymm', '2vlj', '2nx5', '2vlk', '2vlr', '2pye', '2p5e', '2p5w', '2gj6', '2esv', '2ian', '2iam', '1zgl', '3dxa', '1ao7', '1lp9', '2bnr', '2bnq', '2uwe', '2jcc', '2j8u', '2f54', '2f53', '2ak4', '3ffc', '3gsn', '3kps', '3kpr', '3kxf', '3o6f', '3o4l', '3pwp', '3h9s', '3pl6', '3hg1', '3utt', '3sjv', '2wbj', '4gg6', '4h1l', '2ypl', '3d39', '3d3v', '4g8g', '3qfj', '4g9f', '4jrx', '4jry', '4jff', '4jfd', '4jfe', '4ftv', '3vxr', '3w0w', '3vxs', '3vxu', '3vxm', '4mnq', '3mv7', '3mv8', '3mv9', '4ozi', '4ozh', '4ozg', '4ozf', '4mji', '4prh', '4prp', '4pri', '4p4k', '4l3e', '3qdm', '3qdg', '3qeq', '3qdj', '4qrp', '4qok', '4qrr', '4grl', '4may', '4z7v', '4z7u', '4z7w', '4y19', '4y1a', '5d2l', '5d2n', '5brz', '5bs0', '5eu6', '5hho', '5hhm', '5e9d', '5c0a', '5c09', '5hyj', '5c0c', '5c08', '5c07', '5c0b', '5ks9', '5ksa', '5ksb', '5men', '5isz', '5jhd', '5euo', '5e6i', '5jzi', '5tez', '5wkf', '5wkh', '5w1v', '5w1w', '5nme', '5nmf', '5nmg', '5xov', '5xot', '6avf', '6avg', '6cql', '6cqq', '6cqr', '6cqn', '6bj3', '6bj2', '6bj8', '3uts', '6amu', '6am5', '6d7g', '6mtm', '6dkp', '6d78', '6dfx', '6eqa', '6eqb', '6u3n', '6u3o', '6py2', '6px6', '6rpb', '6rp9', '6rsy', '6r2l', '6vrm', '6vrn', '6vqo', '6tro', '6ulr', '6uon', '6uln', '6vmx', '6uk4', '6uk2', '6tmo', '6uz1', '6vm7', '6vma', '6vm9', '6vmc', '6vm8', '6v1a', '6v18', '6v13', '6v19', '6v0y', '6v15', '7n6e', '6xcp', '6xco', '6xc9', '6q3s', '7n1f', '7n1e', '7rm4', '7sg1', '7sg2', '7sg0', '7l1d', '7rrg', '7su9', '7pbe', '7pb2', '7ow6', '7ow5', '7n2s', '7n2n', '7n2r', '7n2p', '7n2o', '7n2q', '8cx4', '8gom', '8gon', '7pdw', '7pbc', '7qpj', '7rk7', '7t2b', '7t2c', '7t2d', '8shi', '8es8', '8es9', '7q9b', '7q9a', '7q99', '8i5c', '8i5d', '8dnt', '8wte', '8wul', '8pjg', '8qfy', '8trq', '8trr', '8trl', '8ye4', '8vcx', '8vcy', '8vd0', '8vd2', '7nme', '7nmf', '7nmg', '8rlt', '8rlu', '8rlv', '8yiv', '8yj2', '9dl1']
VDJdb 203 ['6avf', '6avg', '5eu6', '5wkf', '5wkh', '6mt3', '8rnh', '8rop', '8rng', '8vcx', '8vcy', '8vd0', '8vd2', '6xcp', '5euo', '1bd2', '1fyt', '1j8h', '1mi5', '1oga', '1zgl', '2ak4', '2bnq', '2bnr', '2esv', '2f53', '2f54', '2iam', '2ian', '2nx5', '2p5e', '2p5w', '2pye', '2vlj', '2vlk', '2vlr', '2xn9', '2ypl', '3dxa', '3ffc', '3gsn', '3hg1', '3kpr', '3kps', '3kxf', '3mv7', '3mv8', '3mv9', '3o4l', '3qdg', '3qdj', '3qdm', '3qeq', '3sjv', '3uts', '3utt', '3vxm', '3vxr', '3vxs', '4c56', '4eup', '4g8g', '4g9f', '4gg6', '4jrx', '4jry', '4l3e', '4mji', '4mnq', '4ozf', '4ozg', '4ozh', '4ozi', '4prh', '4pri', '4prp', '4qok', '4qrp', '4y19', '4y1a', '4z7u', '4z7v', '4z7w', '5d2l', '5d2n', '1lp9', '1ymm', '2j8u', '2jcc', '2uwe', '2wbj', '3nfj', '3o6f', '3pl6', '3t0e', '4euq', '4grl', '4h1l', '4may', '4p4k', '4qrr', '4wuu', '4zez', '5c07', '5c08', '5c09', '5c0a', '5c0b', '5c0c', '5e6i', '5hhm', '5hho', '5hyj', '5isz', '5jhd', '5jzi', '5ks9', '5ksa', '5ksb', '5men', '5nht', '5nme', '5nmf', '5nmg', '5nqk', '5tez', '5w1v', '5w1w', '5xot', '5xov', '5yxn', '5yxu', '6am5', '6amu', '6bj2', '6bj3', '6bj8', '6cql', '6cqn', '6cqq', '6cqr', '6d78', '6dfx', '6dkp', '6dxf', '6eqa', '6mtm', '6p64', '6px6', '6py2', '6q3s', '6r2l', '6rp9', '6rpa', '6rsy', '6tro', '6u3n', '6u3o', '6uon', '6vm7', '6vm8', '6vma', '6vmc', '6vmx', '6vqo', '6vrm', '6vrn', '7n1e', '7n1f', '7n6e', '6xc9', '6xco', '6zkw', '6zkx', '6zky', '6zkz', '7dzm', '7dzn', '7ndq', '7ndu', '7rm4', '7rtr', '7l1d', '7sg0', '7sg1', '7sg2', '7rrg', '7n2s', '7n2n', '7n2o', '7n2r', '7n2p', '7n2q', '8cx4', '8v51', '8v50', '8v4z', '8en8', '8enh', '8eo8', '6ulr', '6uln', '6ulk']

,TRAIT_MHC_A,TRAIT_MHC_B,STCRDab_compound,TCR3d_MHC_allele,TRAIT_MHCname,IEDB_mhc,VDJdb_mhc.a,VDJdb_mhc.b
pdb,,,,,,,,
7sg2,HLA-DQA1*05,HLA-DQB1*02,HLA-DQ2-OMEGA1,HLA-DQ2,NaN,HLA-DQA1*05:01/DQB1*02:01,HLA-DQA1*05,HLA-DQB1*02
7sg0,HLA-DQA1*05,HLA-DQB1*02,NaN,HLA-DQ2,NaN,HLA-DQA1*05:01/DQB1*02:01,HLA-DQA1*05,HLA-DQB1*02
7rtr,HLA-A*02:01,B2M,HLA-A*02:01,HLA-A*02,NaN,NaN,HLA-A*02:01,B2M
7rrg,HLA-A*03:01,B2M,NaN,HLA-A*03,NaN,HLA-A*03:01,HLA-A*03:01,B2M
7rm4,HLA-A*02,B2M,P53R175H-HLA-A2,HLA-A*02,NaN,HLA-A*02:01,HLA-A*02,B2M
...,...,...,...,...,...,...,...,...
6mt3,NaN,NaN,NaN,NaN,NaN,NaN,HLA-B*18:01,B2M
8rnh,NaN,NaN,NaN,NaN,NaN,NaN,HLA-B*18:01,B2M
8rop,NaN,NaN,NaN,NaN,NaN,NaN,HLA-B*18:01,B2M
8rng,NaN,NaN,NaN,NaN,NaN,NaN,HLA-B*18:01,B2M
4wuu,NaN,NaN,NaN,NaN,NaN,NaN,HLA-A*02:01:48,B2M

In [90]:
with open('newpdb_name.txt', 'r') as f:
    target_pdbs = f.read().split()
    
target_df = pd.DataFrame(index=[i.lower() for i in target_pdbs], columns=hla_df.columns)
target_df['RAW_PDB']=target_pdbs
target_df

,TRAIT_MHC_A,TRAIT_MHC_B,STCRDab_compound,TCR3d_MHC_allele,TRAIT_MHCname,IEDB_mhc,VDJdb_mhc.a,VDJdb_mhc.b,RAW_PDB
1lp9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1LP9
1zgl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1ZGL
1ao7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1ao7
1bd2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1bd2
1fyt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1fyt
...,...,...,...,...,...,...,...,...,...
8vd0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8vd0
8vd2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8vd2
8yiv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8yiv
8yj2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8yj2
9c3e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9c3e

In [91]:
pdbs = hla_df.index.tolist()

know_pdbs = list(set(target_df.index.tolist()) & set(hla_df.index.tolist()))

target_df.loc[know_pdbs, hla_df.columns] = hla_df.loc[know_pdbs]

target_df

,TRAIT_MHC_A,TRAIT_MHC_B,STCRDab_compound,TCR3d_MHC_allele,TRAIT_MHCname,IEDB_mhc,VDJdb_mhc.a,VDJdb_mhc.b,RAW_PDB
1lp9,HLA-A*02:01:48,B2M,P1049/HLA-A2.1,HLA-A*02,HLA-A*02:01,HLA-A*02:01,HLA-A*02:01:48,B2M,1LP9
1zgl,HLA-DRA*01:02:03,HLA-DRB5*01:01:01,MBP/HLA-DR2A,HLA-DR2a,NaN,HLA-DRA*01:01/DRB5*01:01,HLA-DRA*01:02:03,HLA-DRB5*01:01:01,1ZGL
1ao7,HLA-A*02:01:59,B2M,HLA-A,HLA-A*02,HLA-A*02:01,HLA-A*02:01,NaN,NaN,1ao7
1bd2,HLA-A*02:01:48,B2M,HLA-A,HLA-A*02,HLA-A*02:01,HLA-A*02:01,HLA-A*02:01:48,B2M,1bd2
1fyt,HLA-DRA*01:02:03,HLA-DRB1*01:01:01,HLA-DR1,HLA-DR1,HLA-DRA*01:01 | HLA-DRB1*01:01,HLA-DRB1*01:01,HLA-DRA*01:02:03,HLA-DRB1*01:01:01,1fyt
...,...,...,...,...,...,...,...,...,...
8vd0,NaN,NaN,NaN,HLA-DQ8,NaN,HLA-DQA1*03:01/DQB1*03:02,HLA-DQA1*03:01,HLA-DQB1*02:01,8vd0
8vd2,NaN,NaN,NaN,HLA-DQ8,NaN,HLA-DQA1*03:01/DQB1*03:02,HLA-DQA1*03:01,HLA-DQB1*02:01,8vd2
8yiv,NaN,NaN,NaN,HLA,NaN,HLA-A*01:01,NaN,NaN,8yiv
8yj2,NaN,NaN,NaN,HLA,NaN,HLA-A*01:01,NaN,NaN,8yj2
9c3e,NaN,NaN,NaN,HLA,NaN,NaN,NaN,NaN,9c3e

In [ ]:
target_df.to_csv('hla.csv')